// Generated code stub for web compatibility
// This file is generated by build_runner
// DO NOT MODIFY BY HAND
// ignore_for_file: unused_element

part of 'todo_model.dart';

// Stub for web
const _todoModelSchemaStub = null;
